# Generated by Django 3.0.2 on 2020-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='turn_count',
        ),
        migrations.AddField(
            model_name='membership',
            name='gifted_turns',
            field=models.IntegerField(default=0),
        ),
    ]
