# Generated by Django 3.0.6 on 2020-05-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0002_auto_20200505_0538'),
        ('whoseturn', '0002_auto_20200505_0736'),
    ]

    operations = [
    ]
