# Generated by Django 3.0.2 on 2020-02-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0002_auto_20200225_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=21)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoseturn.Task')),
            ],
        ),
    ]
