# Generated by Django 3.0.2 on 2020-02-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0002_auto_20200226_0617'),
    ]

    operations = [
    ]
