# Generated by Django 3.0.2 on 2020-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0003_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(max_length=22),
        ),
    ]
