# Generated by Django 3.0.2 on 2020-02-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0005_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(max_length=43),
        ),
    ]
