# Generated by Django 3.0.2 on 2020-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0006_auto_20200227_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='turn_count',
            field=models.IntegerField(default=-1),
        ),
    ]
