# Generated by Django 3.0.2 on 2020-02-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0007_membership_turn_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='gifted_turns',
        ),
    ]
