# Generated by Django 3.0.2 on 2020-02-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0008_remove_membership_gifted_turns'),
    ]

    operations = [
    ]
