# Generated by Django 3.0.2 on 2020-03-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0010_auto_20200229_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='invite',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
