# Generated by Django 3.0.2 on 2020-04-09 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoseturn', '0011_auto_20200302_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-date', '-timestamp']},
        ),
        migrations.AddField(
            model_name='logentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
